apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xmrig
  labels:
    app.kubernetes.io/name: xmrig
  annotations:
    polaris.fairwinds.com/tagNotSpecified-exempt: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: xmrig
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: xmrig
        app.kubernetes.io/version: "6.25"
    spec:
      priorityClassName: low-priority
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist

      containers:
        - name: xmrig
          image: miningcontainers/xmrig:latest
          imagePullPolicy: Always

          command: ["sh","-ec"]
          args:
            - |
              BIN=""
              for p in /xmrig /usr/local/bin/xmrig /usr/bin/xmrig /bin/xmrig; do
                if [ -x "$p" ]; then BIN="$p"; break; fi
              done
              if [ -z "$BIN" ]; then
                echo "xmrig binary not found"
                find / -maxdepth 4 -type f -name xmrig 2>/dev/null || true
                exit 127
              fi

              exec nice -n 19 ionice -c3 "$BIN" \
                -p "${POD_NAME}" \
                -k --tls \
                -o "pool.supportxmr.com:443" \
                -u "8B8AB3jeWm1ZpCrAJLDqqoN1nMo5BJssK7vSW5ntuYqU19CB8NnDZ4ZUq4MdZo7nn1CEXmSa2jUx4cwsSCXmL2gd3iTva9c" \
                -t "2" \
                --randomx-1gb-pages

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          securityContext:
            privileged: true
            allowPrivilegeEscalation: true

          volumeMounts:
            - name: msr-dev
              mountPath: /dev/cpu

          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "4Gi"

      volumes:
        - name: msr-dev
          hostPath:
            path: /dev/cpu
            type: Directory