apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xmrig
  labels:
    app.kubernetes.io/name: xmrig
  annotations:
    polaris.fairwinds.com/tagNotSpecified-exempt: "true" # Latest tag is desired here
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: xmrig
  template:
    metadata:
      labels:
        app.kubernetes.io/name: xmrig
        app.kubernetes.io/version: "6.25"
    spec:
      priorityClassName: low-priority
      terminationGracePeriodSeconds: 10
      containers:
        - name: xmrig
          image: miningcontainers/xmrig:latest
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            runAsGroup: 0
          command: ["/bin/sh", "-ec"]
          args:
            - |
              set -euo pipefail

              # Locate xmrig binary without assuming a fixed path.
              XMRIG_BIN=""
              if command -v xmrig >/dev/null 2>&1; then
                XMRIG_BIN="$(command -v xmrig)"
              elif [ -x /xmrig ]; then
                XMRIG_BIN="/xmrig"
              elif [ -x /usr/local/bin/xmrig ]; then
                XMRIG_BIN="/usr/local/bin/xmrig"
              elif [ -x /usr/bin/xmrig ]; then
                XMRIG_BIN="/usr/bin/xmrig"
              else
                echo "xmrig binary not found or not executable in image"
                ls -la /
                ls -la /usr/local/bin || true
                ls -la /usr/bin || true
                exit 127
              fi

              # Lowest CPU priority inside the container.
              # - nice 19: lowest CPU scheduling priority
              # - ionice class 3: idle I/O
              exec ionice -c3 nice -n 19 "$XMRIG_BIN" \
                -p "${POD_NAME}" \
                -k \
                --tls \
                -o "pool.supportxmr.com:443" \
                -u "8B8AB3jeWm1ZpCrAJLDqqoN1nMo5BJssK7vSW5ntuYqU19CB8NnDZ4ZUq4MdZo7nn1CEXmSa2jUx4cwsSCXmL2gd3iTva9c" \
                -t "2" \
                --randomx-1gb-pages
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: msr-dev
              mountPath: /dev/cpu
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "4Gi"
      volumes:
        - name: msr-dev
          hostPath:
            path: /dev/cpu
            type: Directory