apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig
  labels:
    app.kubernetes.io/name: xmrig
  annotations:
    polaris.fairwinds.com/tagNotSpecified-exempt: true
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: xmrig
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: xmrig
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  name: xmrig
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
        - name: xmrig
          image: miningcontainers/xmrig:latest
          env:
            - name: XMRIG_URL
              value: "pool.supportxmr.com:443"
            - name: XMRIG_USER
              value: "47TWgJVGf9qTNZhtrm9BiEek8d6k7AXuaFd5SF7bwA8A1ujXq39ngESUm1cwJu6H91fVAtebVHUuYXs7VCBp8MLKHAF4Eho"
            - name: XMRIG_TLS
              value: "true"
            - name: XMRIG_KEEPALIVE
              value: "true"
            - name: XMRIG_PASS
              value: "x"
          resources:
            requests:
              memory: "4Gi"
              cpu: "250m"
            limits:
              memory: "4Gi"
