spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: xmrig
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: xmrig
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: farh.net/intel-cpu-gen
                operator: Gt
                values:
                - "9"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  name: xmrig
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
        - name: xmrig
          image: miningcontainers/xmrig:latest
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - "-k"
            - "--tls"
            - "-o"
            - "pool.supportxmr.com:443"
            - "-u"
            - "47TWgJVGf9qTNZhtrm9BiEek8d6k7AXuaFd5SF7bwA8A1ujXq39ngESUm1cwJu6H91fVAtebVHUuYXs7VCBp8MLKHAF4Eho"
            - "-t"
            - "2"
            - "--randomx-1gb-pages"
            - "--rig-id=$(POD_NAME)"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: msr-dev
              mountPath: /dev/cpu
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
      volumes:
        - name: msr-dev
          hostPath:
            path: /dev/cpu
            type: Directory
