apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - xmrig
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: xmrig
          image: xmrig/xmrig:latest
          command: ["/xmrig"]
          args:
            - "-o"
            - "xmrig-proxy:3333"
            - "-u"
            - "worker1"
            - "-k"
            - "--keepalive"
            - "--coin"
            - "monero"
          resources:
            limits:
              memory: "4Gi"
